name: Run Python Tests

on:
  push:
    branches: [ main ]  # or your default branch
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Python unittest
        run: |
          cd GDC-Level-2-Milestone-master
          python3 test.py
